[2025-04-09T22:09:10.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T22:09:10.194+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-09T22:08:00+00:00 [queued]>
[2025-04-09T22:09:10.209+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-09T22:08:00+00:00 [queued]>
[2025-04-09T22:09:10.209+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T22:09:10.220+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_wind_data> on 2025-04-09 22:08:00+00:00
[2025-04-09T22:09:10.225+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18974) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T22:09:10.226+0000] {standard_task_runner.py:72} INFO - Started process 18994 to run task
[2025-04-09T22:09:10.230+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'insert_wind_data', 'scheduled__2025-04-09T22:08:00+00:00', '--job-id', '1294', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpjlkyqd33']
[2025-04-09T22:09:10.234+0000] {standard_task_runner.py:105} INFO - Job 1294: Subtask insert_wind_data
[2025-04-09T22:09:10.293+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-09T22:08:00+00:00 [running]> on host 970813cff045
[2025-04-09T22:09:10.360+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_wind_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T22:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-09T22:08:00+00:00'
[2025-04-09T22:09:10.361+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T22:09:10.375+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-09T22:09:10.780+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-09T22:09:10.785+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T22:09:10.786+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=insert_wind_data, run_id=scheduled__2025-04-09T22:08:00+00:00, execution_date=20250409T220800, start_date=20250409T220910, end_date=20250409T220910
[2025-04-09T22:09:10.824+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T22:09:10.851+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-09T22:09:10.853+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
