[2025-04-08T21:35:38.480+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:35:38.495+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T21:34:00+00:00 [queued]>
[2025-04-08T21:35:38.502+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T21:34:00+00:00 [queued]>
[2025-04-08T21:35:38.506+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:35:38.515+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2025-04-08 21:34:00+00:00
[2025-04-08T21:35:38.520+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22616) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:35:38.521+0000] {standard_task_runner.py:72} INFO - Started process 22618 to run task
[2025-04-08T21:35:38.522+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'insert_weather_data', 'scheduled__2025-04-08T21:34:00+00:00', '--job-id', '962', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmp1n1_o_go']
[2025-04-08T21:35:38.523+0000] {standard_task_runner.py:105} INFO - Job 962: Subtask insert_weather_data
[2025-04-08T21:35:38.559+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T21:34:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:35:38.608+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:34:00+00:00'
[2025-04-08T21:35:38.609+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:35:38.620+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:35:38.630+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:35:38.636+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:35:38.637+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=insert_weather_data, run_id=scheduled__2025-04-08T21:34:00+00:00, execution_date=20250408T213400, start_date=20250408T213538, end_date=20250408T213538
[2025-04-08T21:35:38.663+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:35:38.678+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T21:35:38.680+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
