[2025-04-08T21:37:52.617+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:37:52.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:36:00+00:00 [queued]>
[2025-04-08T21:37:52.635+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:36:00+00:00 [queued]>
[2025-04-08T21:37:52.637+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:37:52.650+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_weather_table> on 2025-04-08 21:36:00+00:00
[2025-04-08T21:37:52.658+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22819) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:37:52.661+0000] {standard_task_runner.py:72} INFO - Started process 22826 to run task
[2025-04-08T21:37:52.665+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_dim_weather_table', 'scheduled__2025-04-08T21:36:00+00:00', '--job-id', '970', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpu88ow73t']
[2025-04-08T21:37:52.670+0000] {standard_task_runner.py:105} INFO - Job 970: Subtask create_dim_weather_table
[2025-04-08T21:37:52.736+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:36:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:37:52.828+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_dim_weather_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:36:00+00:00'
[2025-04-08T21:37:52.832+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:37:52.873+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:37:52.898+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:37:52.905+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:37:52.906+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_dim_weather_table, run_id=scheduled__2025-04-08T21:36:00+00:00, execution_date=20250408T213600, start_date=20250408T213752, end_date=20250408T213752
[2025-04-08T21:37:52.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:37:52.950+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
