[2025-04-09T21:50:03.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T21:50:03.293+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:48:00+00:00 [queued]>
[2025-04-09T21:50:03.304+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:48:00+00:00 [queued]>
[2025-04-09T21:50:03.306+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T21:50:03.317+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): aggregate_and_insert_fact_data> on 2025-04-09 21:48:00+00:00
[2025-04-09T21:50:03.321+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17032) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T21:50:03.322+0000] {standard_task_runner.py:72} INFO - Started process 17035 to run task
[2025-04-09T21:50:03.322+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'aggregate_and_insert_fact_data', 'scheduled__2025-04-09T21:48:00+00:00', '--job-id', '1274', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpib5qipdo']
[2025-04-09T21:50:03.323+0000] {standard_task_runner.py:105} INFO - Job 1274: Subtask aggregate_and_insert_fact_data
[2025-04-09T21:50:03.355+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:48:00+00:00 [running]> on host 970813cff045
[2025-04-09T21:50:03.409+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_and_insert_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T21:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-09T21:48:00+00:00'
[2025-04-09T21:50:03.410+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T21:50:03.425+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-09T21:50:03.435+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-09T21:50:03.441+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T21:50:03.442+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=aggregate_and_insert_fact_data, run_id=scheduled__2025-04-09T21:48:00+00:00, execution_date=20250409T214800, start_date=20250409T215003, end_date=20250409T215003
[2025-04-09T21:50:03.461+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T21:50:03.474+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T21:50:03.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
