[2025-04-08T21:38:01.264+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:38:01.277+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_fact_table scheduled__2025-04-08T21:37:00+00:00 [queued]>
[2025-04-08T21:38:01.283+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_fact_table scheduled__2025-04-08T21:37:00+00:00 [queued]>
[2025-04-08T21:38:01.284+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:38:01.301+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_fact_table> on 2025-04-08 21:37:00+00:00
[2025-04-08T21:38:01.307+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22865) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:38:01.309+0000] {standard_task_runner.py:72} INFO - Started process 22876 to run task
[2025-04-08T21:38:01.310+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_fact_table', 'scheduled__2025-04-08T21:37:00+00:00', '--job-id', '982', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpgqd8cj57']
[2025-04-08T21:38:01.313+0000] {standard_task_runner.py:105} INFO - Job 982: Subtask create_fact_table
[2025-04-08T21:38:01.358+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_fact_table scheduled__2025-04-08T21:37:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:38:01.421+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:37:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:37:00+00:00'
[2025-04-08T21:38:01.421+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:38:01.435+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:38:01.444+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:38:01.450+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:38:01.450+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_fact_table, run_id=scheduled__2025-04-08T21:37:00+00:00, execution_date=20250408T213700, start_date=20250408T213801, end_date=20250408T213801
[2025-04-08T21:38:01.492+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:38:01.498+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
