[2025-04-08T17:25:29.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T17:25:29.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_hook_create_table.create_pet_table scheduled__2025-04-08T17:24:00+00:00 [queued]>
[2025-04-08T17:25:29.615+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_hook_create_table.create_pet_table scheduled__2025-04-08T17:24:00+00:00 [queued]>
[2025-04-08T17:25:29.615+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T17:25:29.621+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_pet_table> on 2025-04-08 17:24:00+00:00
[2025-04-08T17:25:29.626+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4603) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T17:25:29.625+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_hook_create_table', 'create_pet_table', 'scheduled__2025-04-08T17:24:00+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpf89nzb6_']
[2025-04-08T17:25:29.627+0000] {standard_task_runner.py:105} INFO - Job 756: Subtask create_pet_table
[2025-04-08T17:25:29.626+0000] {standard_task_runner.py:72} INFO - Started process 4604 to run task
[2025-04-08T17:25:29.652+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_hook_create_table.create_pet_table scheduled__2025-04-08T17:24:00+00:00 [running]> on host 970813cff045
[2025-04-08T17:25:29.694+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_hook_create_table' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T17:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T17:24:00+00:00'
[2025-04-08T17:25:29.695+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T17:25:29.706+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T17:25:29.719+0000] {logging_mixin.py:190} INFO - Connecting to: postgresql://***:***@host.docker.internal:5432/***
[2025-04-08T17:25:29.720+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T17:25:29.724+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T17:25:29.724+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_hook_create_table, task_id=create_pet_table, run_id=scheduled__2025-04-08T17:24:00+00:00, execution_date=20250408T172400, start_date=20250408T172529, end_date=20250408T172529
[2025-04-08T17:25:29.770+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T17:25:29.779+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T17:25:29.779+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
