[2025-03-18T10:30:30.821+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:30:30.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T10:30:30.828+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:30:30.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:30:30.851+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:30:30.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T10:30:30.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:30:30.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.060 seconds
[2025-03-18T10:31:01.213+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:01.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T10:31:01.224+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:31:01.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:01.234+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:31:01.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T10:31:01.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:01.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.049 seconds
[2025-03-18T10:31:31.647+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:31.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T10:31:31.650+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:31:31.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:31.659+0000] {logging_mixin.py:190} INFO - [2025-03-18T10:31:31.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T10:31:31.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T10:31:31.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:21:08.624+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:08.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:21:08.628+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:21:08.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:08.640+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:21:08.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:21:08.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:08.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.041 seconds
[2025-03-18T11:21:38.994+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:38.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:21:39.009+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:21:39.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:39.022+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:21:39.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:21:39.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:21:39.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.053 seconds
[2025-03-18T11:22:09.425+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:09.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:22:09.428+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:22:09.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:09.437+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:22:09.434+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:22:09.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:09.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.036 seconds
[2025-03-18T11:22:39.882+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:39.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:22:39.885+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:22:39.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:39.895+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:22:39.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:22:39.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:22:39.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:23:10.296+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:10.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:23:10.298+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:23:10.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:10.309+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:23:10.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:23:10.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:10.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:23:40.727+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:40.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:23:40.730+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:23:40.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:40.740+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:23:40.736+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:23:40.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:23:40.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.039 seconds
[2025-03-18T11:24:11.125+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:11.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:24:11.130+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:24:11.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:11.143+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:24:11.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:24:11.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:11.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.041 seconds
[2025-03-18T11:24:41.549+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:41.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:24:41.552+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:24:41.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:41.562+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:24:41.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:24:41.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:24:41.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T11:25:12.002+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:12.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:25:12.005+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:25:12.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:12.016+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:25:12.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:25:12.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:12.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:25:42.388+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:42.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:25:42.391+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:25:42.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:42.399+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:25:42.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:25:42.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:25:42.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:26:12.794+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:12.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:26:12.797+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:26:12.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:12.807+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:26:12.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:26:12.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:12.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:26:43.254+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:43.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:26:43.258+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:26:43.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:43.267+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:26:43.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:26:43.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:26:43.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:27:13.591+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:13.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:27:13.595+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:27:13.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:13.606+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:27:13.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:27:13.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:13.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.040 seconds
[2025-03-18T11:27:43.973+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:43.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:27:43.976+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:27:43.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:43.985+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:27:43.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:27:43.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:27:44.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:28:14.384+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:14.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:28:14.386+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:28:14.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:14.393+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:28:14.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:28:14.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:14.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.025 seconds
[2025-03-18T11:28:44.762+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:44.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:28:44.767+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:28:44.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:44.779+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:28:44.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:28:44.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:28:44.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.040 seconds
[2025-03-18T11:29:15.180+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:15.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:29:15.189+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:29:15.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:15.216+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:29:15.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:29:15.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:15.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.100 seconds
[2025-03-18T11:29:45.703+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:45.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:29:45.708+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:29:45.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:45.719+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:29:45.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:29:45.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:29:45.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.039 seconds
[2025-03-18T11:30:16.121+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:16.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:30:16.124+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:30:16.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:16.134+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:30:16.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:30:16.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:16.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:30:46.520+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:46.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:30:46.523+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:30:46.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:46.532+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:30:46.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:30:46.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:30:46.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:31:16.962+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:16.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:31:16.972+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:31:16.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:16.981+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:31:16.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:31:16.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:17.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.047 seconds
[2025-03-18T11:31:47.378+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:47.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:31:47.384+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:31:47.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:47.392+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:31:47.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:31:47.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:31:47.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:32:17.816+0000] {processor.py:186} INFO - Started process (PID=529) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:17.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:32:17.818+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:32:17.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:17.827+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:32:17.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:32:17.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:17.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:32:48.235+0000] {processor.py:186} INFO - Started process (PID=545) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:48.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:32:48.238+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:32:48.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:48.247+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:32:48.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:32:48.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:32:48.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:33:18.633+0000] {processor.py:186} INFO - Started process (PID=561) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:18.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:33:18.636+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:33:18.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:18.645+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:33:18.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:33:18.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:18.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:33:34.846+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:34.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:33:34.848+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:33:34.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:34.856+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:33:34.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:33:34.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:33:34.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.029 seconds
[2025-03-18T11:34:05.201+0000] {processor.py:186} INFO - Started process (PID=587) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:05.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:34:05.207+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:34:05.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:05.221+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:34:05.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:34:05.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:05.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.040 seconds
[2025-03-18T11:34:35.635+0000] {processor.py:186} INFO - Started process (PID=603) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:35.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:34:35.639+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:34:35.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:35.648+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:34:35.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:34:35.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:34:35.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:35:06.030+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:06.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:35:06.034+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:35:06.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:06.046+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:35:06.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:35:06.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:06.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:35:36.441+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:36.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:35:36.444+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:35:36.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:36.453+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:35:36.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:35:36.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:35:36.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T11:36:06.824+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:06.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:36:06.827+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:36:06.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:06.836+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:36:06.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:36:06.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:06.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T11:36:37.206+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:37.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:36:37.207+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:36:37.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:37.214+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:36:37.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:36:37.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:36:37.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.025 seconds
[2025-03-18T11:37:07.544+0000] {processor.py:186} INFO - Started process (PID=683) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:07.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:37:07.546+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:37:07.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:07.552+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:37:07.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:37:07.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:07.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.028 seconds
[2025-03-18T11:37:37.976+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:37.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:37:37.980+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:37:37.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:37.989+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:37:37.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:37:37.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:37:38.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:38:08.400+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:08.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:38:08.403+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:38:08.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:08.414+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:38:08.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:38:08.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:08.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:38:38.763+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:38.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:38:38.766+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:38:38.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:38.774+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:38:38.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:38:38.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:38:38.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T11:39:09.165+0000] {processor.py:186} INFO - Started process (PID=748) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:09.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:39:09.169+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:39:09.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:09.179+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:39:09.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:39:09.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:09.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:39:39.554+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:39.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:39:39.557+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:39:39.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:39.566+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:39:39.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:39:39.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:39:39.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:40:09.888+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:09.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:40:09.892+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:40:09.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:09.901+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:40:09.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:40:09.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:09.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:40:40.335+0000] {processor.py:186} INFO - Started process (PID=795) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:40.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:40:40.337+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:40:40.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:40.342+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:40:40.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:40:40.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:40:40.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.021 seconds
[2025-03-18T11:41:10.761+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:10.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:41:10.764+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:41:10.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:10.773+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:41:10.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:41:10.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:10.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:41:41.163+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:41.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:41:41.166+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:41:41.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:41.175+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:41:41.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:41:41.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:41:41.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T11:42:11.569+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:11.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:42:11.572+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:42:11.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:11.582+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:42:11.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:42:11.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:11.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T11:42:41.965+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:41.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:42:41.968+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:42:41.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:41.978+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:42:41.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:42:41.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:42:41.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:43:12.317+0000] {processor.py:186} INFO - Started process (PID=875) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:12.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:43:12.320+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:43:12.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:12.329+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:43:12.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:43:12.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:12.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:43:42.716+0000] {processor.py:186} INFO - Started process (PID=891) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:42.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:43:42.720+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:43:42.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:42.729+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:43:42.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:43:42.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:43:42.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:44:13.100+0000] {processor.py:186} INFO - Started process (PID=913) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:13.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:44:13.102+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:44:13.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:13.110+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:44:13.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:44:13.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:13.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.026 seconds
[2025-03-18T11:44:43.508+0000] {processor.py:186} INFO - Started process (PID=929) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:43.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:44:43.510+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:44:43.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:43.517+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:44:43.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:44:43.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:44:43.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.024 seconds
[2025-03-18T11:45:13.903+0000] {processor.py:186} INFO - Started process (PID=945) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:13.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:45:13.906+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:45:13.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:13.916+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:45:13.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:45:13.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:13.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:45:44.265+0000] {processor.py:186} INFO - Started process (PID=961) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:44.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:45:44.267+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:45:44.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:44.276+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:45:44.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:45:44.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:45:44.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:46:14.578+0000] {processor.py:186} INFO - Started process (PID=977) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:14.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:46:14.583+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:46:14.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:14.593+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:46:14.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:46:14.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:14.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T11:46:44.990+0000] {processor.py:186} INFO - Started process (PID=993) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:44.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:46:44.994+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:46:44.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:45.004+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:46:45.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:46:45.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:46:45.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:47:15.378+0000] {processor.py:186} INFO - Started process (PID=1009) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:15.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:47:15.381+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:47:15.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:15.391+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:47:15.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:47:15.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:15.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:47:45.766+0000] {processor.py:186} INFO - Started process (PID=1025) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:45.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:47:45.769+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:47:45.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:45.781+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:47:45.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:47:45.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:47:45.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:48:16.142+0000] {processor.py:186} INFO - Started process (PID=1041) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:16.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:48:16.144+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:48:16.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:16.152+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:48:16.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:48:16.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:16.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.027 seconds
[2025-03-18T11:48:46.543+0000] {processor.py:186} INFO - Started process (PID=1057) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:46.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:48:46.545+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:48:46.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:46.552+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:48:46.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:48:46.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:48:46.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.025 seconds
[2025-03-18T11:49:16.907+0000] {processor.py:186} INFO - Started process (PID=1073) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:16.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:49:16.911+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:49:16.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:16.924+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:49:16.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:49:16.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:16.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:49:47.347+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:47.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:49:47.351+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:49:47.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:47.360+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:49:47.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:49:47.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:49:47.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:50:17.745+0000] {processor.py:186} INFO - Started process (PID=1105) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:17.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:50:17.750+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:50:17.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:17.764+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:50:17.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:50:17.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:17.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.041 seconds
[2025-03-18T11:50:48.134+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:48.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:50:48.139+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:50:48.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:48.148+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:50:48.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:50:48.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:50:48.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T11:51:18.546+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:18.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:51:18.551+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:51:18.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:18.563+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:51:18.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:51:18.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:18.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.046 seconds
[2025-03-18T11:51:48.915+0000] {processor.py:186} INFO - Started process (PID=1153) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:48.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:51:48.918+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:51:48.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:48.927+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:51:48.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:51:48.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:51:48.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:52:19.274+0000] {processor.py:186} INFO - Started process (PID=1169) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:19.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:52:19.277+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:52:19.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:19.296+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:52:19.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:52:19.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:19.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.046 seconds
[2025-03-18T11:52:49.683+0000] {processor.py:186} INFO - Started process (PID=1185) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:49.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:52:49.687+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:52:49.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:49.698+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:52:49.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:52:49.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:52:49.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.042 seconds
[2025-03-18T11:53:20.075+0000] {processor.py:186} INFO - Started process (PID=1200) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:20.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:53:20.078+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:53:20.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:20.086+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:53:20.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:53:20.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:20.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:53:50.461+0000] {processor.py:186} INFO - Started process (PID=1216) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:50.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:53:50.463+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:53:50.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:50.474+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:53:50.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:53:50.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:53:50.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.029 seconds
[2025-03-18T11:54:20.859+0000] {processor.py:186} INFO - Started process (PID=1232) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:20.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:54:20.861+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:54:20.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:20.868+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:54:20.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:54:20.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:20.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.026 seconds
[2025-03-18T11:54:51.185+0000] {processor.py:186} INFO - Started process (PID=1248) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:51.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:54:51.190+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:54:51.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:51.199+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:54:51.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:54:51.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:54:51.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.037 seconds
[2025-03-18T11:55:21.528+0000] {processor.py:186} INFO - Started process (PID=1264) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:21.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:55:21.530+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:55:21.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:21.539+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:55:21.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:55:21.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:21.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T11:55:51.959+0000] {processor.py:186} INFO - Started process (PID=1280) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:51.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:55:51.963+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:55:51.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:51.974+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:55:51.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:55:51.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:55:51.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T11:56:22.387+0000] {processor.py:186} INFO - Started process (PID=1295) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:22.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:56:22.391+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:56:22.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:22.400+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:56:22.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:56:22.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:22.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T11:56:52.800+0000] {processor.py:186} INFO - Started process (PID=1311) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:52.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:56:52.804+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:56:52.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:52.812+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:56:52.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:56:52.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:56:52.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T11:57:23.229+0000] {processor.py:186} INFO - Started process (PID=1327) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:23.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:57:23.232+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:57:23.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:23.242+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:57:23.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:57:23.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:23.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T11:57:53.576+0000] {processor.py:186} INFO - Started process (PID=1343) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:53.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:57:53.579+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:57:53.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:53.590+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:57:53.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:57:53.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:57:53.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.036 seconds
[2025-03-18T11:58:23.907+0000] {processor.py:186} INFO - Started process (PID=1358) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:23.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:58:23.909+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:58:23.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:23.916+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:58:23.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:58:23.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:23.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.027 seconds
[2025-03-18T11:58:54.300+0000] {processor.py:186} INFO - Started process (PID=1374) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:54.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:58:54.302+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:58:54.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:54.310+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:58:54.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:58:54.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:58:54.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.028 seconds
[2025-03-18T11:59:24.590+0000] {processor.py:186} INFO - Started process (PID=1390) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:24.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:59:24.594+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:59:24.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:24.610+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:59:24.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:59:24.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:24.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.044 seconds
[2025-03-18T11:59:54.944+0000] {processor.py:186} INFO - Started process (PID=1406) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:54.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T11:59:54.947+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:59:54.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:54.958+0000] {logging_mixin.py:190} INFO - [2025-03-18T11:59:54.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T11:59:54.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T11:59:54.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T12:00:25.322+0000] {processor.py:186} INFO - Started process (PID=1422) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:25.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:00:25.325+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:00:25.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:25.331+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:00:25.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:00:25.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:25.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.024 seconds
[2025-03-18T12:00:55.740+0000] {processor.py:186} INFO - Started process (PID=1438) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:55.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:00:55.744+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:00:55.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:55.755+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:00:55.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:00:55.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:00:55.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.040 seconds
[2025-03-18T12:01:26.175+0000] {processor.py:186} INFO - Started process (PID=1454) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:26.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:01:26.179+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:01:26.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:26.194+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:01:26.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:01:26.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:26.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.043 seconds
[2025-03-18T12:01:56.574+0000] {processor.py:186} INFO - Started process (PID=1469) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:56.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:01:56.578+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:01:56.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:56.589+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:01:56.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:01:56.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:01:56.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T12:02:26.970+0000] {processor.py:186} INFO - Started process (PID=1485) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:26.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:02:26.974+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:02:26.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:26.983+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:02:26.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:02:26.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:26.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T12:02:57.366+0000] {processor.py:186} INFO - Started process (PID=1501) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:57.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:02:57.372+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:02:57.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:57.385+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:02:57.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:02:57.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:02:57.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.043 seconds
[2025-03-18T12:03:27.751+0000] {processor.py:186} INFO - Started process (PID=1517) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:27.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:03:27.753+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:03:27.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:27.760+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:03:27.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:03:27.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:27.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:03:58.117+0000] {processor.py:186} INFO - Started process (PID=1533) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:58.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:03:58.119+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:03:58.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:58.127+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:03:58.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:03:58.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:03:58.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.029 seconds
[2025-03-18T12:04:28.552+0000] {processor.py:186} INFO - Started process (PID=1549) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:28.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:04:28.556+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:04:28.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:28.568+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:04:28.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:04:28.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:28.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T12:04:58.930+0000] {processor.py:186} INFO - Started process (PID=1565) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:58.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:04:58.933+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:04:58.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:58.941+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:04:58.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:04:58.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:04:58.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T12:05:29.341+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:29.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:05:29.348+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:05:29.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:29.361+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:05:29.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:05:29.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:29.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.042 seconds
[2025-03-18T12:05:59.713+0000] {processor.py:186} INFO - Started process (PID=1597) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:59.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:05:59.716+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:05:59.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:59.725+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:05:59.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:05:59.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:05:59.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T12:06:30.142+0000] {processor.py:186} INFO - Started process (PID=1618) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:06:30.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:06:30.146+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:06:30.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:06:30.156+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:06:30.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:06:30.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:06:30.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.036 seconds
[2025-03-18T12:07:00.558+0000] {processor.py:186} INFO - Started process (PID=1639) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:00.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:07:00.560+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:07:00.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:00.565+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:07:00.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:07:00.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:00.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.023 seconds
[2025-03-18T12:07:31.001+0000] {processor.py:186} INFO - Started process (PID=1660) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:31.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:07:31.004+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:07:31.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:31.011+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:07:31.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:07:31.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:07:31.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T12:08:01.663+0000] {processor.py:186} INFO - Started process (PID=1686) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:01.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:08:01.666+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:08:01.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:01.675+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:08:01.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:08:01.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:01.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.034 seconds
[2025-03-18T12:08:32.017+0000] {processor.py:186} INFO - Started process (PID=1707) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:32.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:08:32.021+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:08:32.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:32.035+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:08:32.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:08:32.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:08:32.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.041 seconds
[2025-03-18T12:09:02.407+0000] {processor.py:186} INFO - Started process (PID=1728) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:02.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:09:02.414+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:09:02.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:02.447+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:09:02.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:09:02.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:02.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.056 seconds
[2025-03-18T12:09:32.815+0000] {processor.py:186} INFO - Started process (PID=1749) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:32.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:09:32.817+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:09:32.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:32.823+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:09:32.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:09:32.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:09:32.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.026 seconds
[2025-03-18T12:10:03.176+0000] {processor.py:186} INFO - Started process (PID=1770) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:03.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:10:03.178+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:10:03.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:03.185+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:10:03.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:10:03.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:03.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.030 seconds
[2025-03-18T12:10:33.609+0000] {processor.py:186} INFO - Started process (PID=1791) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:33.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:10:33.613+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:10:33.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:33.622+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:10:33.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:10:33.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:10:33.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:11:04.070+0000] {processor.py:186} INFO - Started process (PID=1812) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:04.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:11:04.074+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:11:04.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:04.083+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:11:04.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:11:04.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:04.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:11:34.459+0000] {processor.py:186} INFO - Started process (PID=1833) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:34.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:11:34.462+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:11:34.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:34.472+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:11:34.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:11:34.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:11:34.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T12:12:04.787+0000] {processor.py:186} INFO - Started process (PID=1854) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:04.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:12:04.790+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:12:04.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:04.796+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:12:04.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:12:04.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:04.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.027 seconds
[2025-03-18T12:12:35.073+0000] {processor.py:186} INFO - Started process (PID=1875) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:35.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:12:35.077+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:12:35.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:35.086+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:12:35.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:12:35.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:12:35.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:13:05.455+0000] {processor.py:186} INFO - Started process (PID=1896) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:05.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:13:05.461+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:13:05.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:05.470+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:13:05.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:13:05.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:05.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T12:13:35.870+0000] {processor.py:186} INFO - Started process (PID=1917) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:35.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:13:35.876+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:13:35.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:35.888+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:13:35.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:13:35.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:13:35.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.042 seconds
[2025-03-18T12:14:06.287+0000] {processor.py:186} INFO - Started process (PID=1938) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:06.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:14:06.291+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:14:06.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:06.299+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:14:06.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:14:06.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:06.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.032 seconds
[2025-03-18T12:14:36.642+0000] {processor.py:186} INFO - Started process (PID=1959) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:36.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:14:36.646+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:14:36.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:36.655+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:14:36.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:14:36.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:14:36.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:15:07.027+0000] {processor.py:186} INFO - Started process (PID=1980) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:07.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:15:07.030+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:15:07.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:07.039+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:15:07.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:15:07.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:07.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T12:15:37.518+0000] {processor.py:186} INFO - Started process (PID=2001) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:37.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:15:37.520+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:15:37.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:37.526+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:15:37.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:15:37.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:15:37.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.024 seconds
[2025-03-18T12:16:53.446+0000] {processor.py:186} INFO - Started process (PID=2025) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:16:53.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:16:53.449+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:16:53.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:16:53.466+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:16:53.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:16:53.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:16:53.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.038 seconds
[2025-03-18T12:17:23.906+0000] {processor.py:186} INFO - Started process (PID=2046) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:23.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:17:23.910+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:17:23.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:23.918+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:17:23.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:17:23.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:23.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.033 seconds
[2025-03-18T12:17:54.364+0000] {processor.py:186} INFO - Started process (PID=2067) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:54.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:17:54.368+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:17:54.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:54.377+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:17:54.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:17:54.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:17:54.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.035 seconds
[2025-03-18T12:18:24.799+0000] {processor.py:186} INFO - Started process (PID=2088) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:24.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:18:24.803+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:18:24.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:24.820+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:18:24.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:18:24.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:24.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.046 seconds
[2025-03-18T12:18:55.342+0000] {processor.py:186} INFO - Started process (PID=2109) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:55.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:18:55.347+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:18:55.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:55.358+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:18:55.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:18:55.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:18:55.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.041 seconds
[2025-03-18T12:19:25.735+0000] {processor.py:186} INFO - Started process (PID=2130) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:25.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:19:25.738+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:19:25.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:25.747+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:19:25.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:19:25.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:25.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T12:19:56.202+0000] {processor.py:186} INFO - Started process (PID=2151) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:56.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:19:56.206+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:19:56.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:56.219+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:19:56.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:19:56.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:19:56.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.043 seconds
[2025-03-18T12:20:26.714+0000] {processor.py:186} INFO - Started process (PID=2172) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:26.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:20:26.719+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:20:26.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:26.737+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:20:26.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:20:26.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:26.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.050 seconds
[2025-03-18T12:20:57.408+0000] {processor.py:186} INFO - Started process (PID=2195) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:57.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:20:57.413+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:20:57.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:57.425+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:20:57.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:20:57.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:20:57.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.042 seconds
[2025-03-18T12:21:27.823+0000] {processor.py:186} INFO - Started process (PID=2216) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:27.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:21:27.825+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:21:27.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:27.832+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:21:27.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:21:27.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:27.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.031 seconds
[2025-03-18T12:21:58.236+0000] {processor.py:186} INFO - Started process (PID=2237) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:58.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:21:58.241+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:21:58.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:58.267+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:21:58.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:21:58.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:21:58.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.054 seconds
[2025-03-18T12:22:28.672+0000] {processor.py:186} INFO - Started process (PID=2258) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:28.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:22:28.677+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:22:28.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:28.691+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:22:28.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:22:28.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:28.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.042 seconds
[2025-03-18T12:22:59.119+0000] {processor.py:186} INFO - Started process (PID=2279) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:59.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:22:59.124+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:22:59.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:59.136+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:22:59.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:22:59.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:22:59.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.045 seconds
[2025-03-18T12:23:29.780+0000] {processor.py:186} INFO - Started process (PID=2305) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:23:29.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:23:29.782+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:23:29.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:23:29.794+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:23:29.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:23:29.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:23:29.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.050 seconds
[2025-03-18T12:24:00.176+0000] {processor.py:186} INFO - Started process (PID=2326) to work on /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:24:00.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_pipeline_lab_2.py for tasks to queue
[2025-03-18T12:24:00.179+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:24:00.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:24:00.187+0000] {logging_mixin.py:190} INFO - [2025-03-18T12:24:00.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_lab_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_lab_2.py", line 13, in <module>
    is_raw_data_file_exists = FileSensor(
                              ^^^^^^^^^^
NameError: name 'FileSensor' is not defined
[2025-03-18T12:24:00.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_lab_2.py
[2025-03-18T12:24:00.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_pipeline_lab_2.py took 0.036 seconds
