[2025-04-08T20:23:01.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T20:23:01.467+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T20:22:00+00:00 [queued]>
[2025-04-08T20:23:01.478+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T20:22:00+00:00 [queued]>
[2025-04-08T20:23:01.478+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T20:23:01.488+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2025-04-08 20:22:00+00:00
[2025-04-08T20:23:01.492+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T20:23:01.492+0000] {standard_task_runner.py:72} INFO - Started process 17324 to run task
[2025-04-08T20:23:01.492+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'insert_weather_data', 'scheduled__2025-04-08T20:22:00+00:00', '--job-id', '830', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpv59bva7r']
[2025-04-08T20:23:01.493+0000] {standard_task_runner.py:105} INFO - Job 830: Subtask insert_weather_data
[2025-04-08T20:23:01.521+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.insert_weather_data scheduled__2025-04-08T20:22:00+00:00 [running]> on host 970813cff045
[2025-04-08T20:23:01.581+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T20:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T20:22:00+00:00'
[2025-04-08T20:23:01.582+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T20:23:01.594+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T20:23:01.616+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T20:23:01.628+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T20:23:01.628+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=insert_weather_data, run_id=scheduled__2025-04-08T20:22:00+00:00, execution_date=20250408T202200, start_date=20250408T202301, end_date=20250408T202301
[2025-04-08T20:23:01.674+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T20:23:01.703+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T20:23:01.706+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
