[2025-04-09T21:26:10.869+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T21:26:10.884+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:24:00+00:00 [queued]>
[2025-04-09T21:26:10.894+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:24:00+00:00 [queued]>
[2025-04-09T21:26:10.894+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T21:26:10.902+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): aggregate_and_insert_fact_data> on 2025-04-09 21:24:00+00:00
[2025-04-09T21:26:10.907+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14495) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T21:26:10.908+0000] {standard_task_runner.py:72} INFO - Started process 14496 to run task
[2025-04-09T21:26:10.907+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'aggregate_and_insert_fact_data', 'scheduled__2025-04-09T21:24:00+00:00', '--job-id', '1227', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmp75c15rf3']
[2025-04-09T21:26:10.909+0000] {standard_task_runner.py:105} INFO - Job 1227: Subtask aggregate_and_insert_fact_data
[2025-04-09T21:26:10.938+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.aggregate_and_insert_fact_data scheduled__2025-04-09T21:24:00+00:00 [running]> on host 970813cff045
[2025-04-09T21:26:10.978+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_and_insert_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T21:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-09T21:24:00+00:00'
[2025-04-09T21:26:10.978+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T21:26:10.989+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-09T21:26:10.999+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-09T21:26:11.004+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T21:26:11.005+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=aggregate_and_insert_fact_data, run_id=scheduled__2025-04-09T21:24:00+00:00, execution_date=20250409T212400, start_date=20250409T212610, end_date=20250409T212611
[2025-04-09T21:26:11.049+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T21:26:11.059+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T21:26:11.059+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
