[2025-04-08T21:35:37.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:35:37.660+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:34:00+00:00 [queued]>
[2025-04-08T21:35:37.671+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:34:00+00:00 [queued]>
[2025-04-08T21:35:37.671+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:35:37.691+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_weather_table> on 2025-04-08 21:34:00+00:00
[2025-04-08T21:35:37.702+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22571) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:35:37.708+0000] {standard_task_runner.py:72} INFO - Started process 22586 to run task
[2025-04-08T21:35:37.708+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_dim_weather_table', 'scheduled__2025-04-08T21:34:00+00:00', '--job-id', '957', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpgk27n7i4']
[2025-04-08T21:35:37.712+0000] {standard_task_runner.py:105} INFO - Job 957: Subtask create_dim_weather_table
[2025-04-08T21:35:37.777+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:34:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:35:37.872+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_dim_weather_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:34:00+00:00'
[2025-04-08T21:35:37.874+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:35:37.894+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:35:37.906+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:35:37.918+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:35:37.919+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_dim_weather_table, run_id=scheduled__2025-04-08T21:34:00+00:00, execution_date=20250408T213400, start_date=20250408T213537, end_date=20250408T213537
[2025-04-08T21:35:37.974+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:35:37.998+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-08T21:35:38.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
