[2025-04-08T21:15:35.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:15:35.448+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-08T21:14:00+00:00 [queued]>
[2025-04-08T21:15:35.457+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-08T21:14:00+00:00 [queued]>
[2025-04-08T21:15:35.458+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:15:35.469+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_wind_data> on 2025-04-08 21:14:00+00:00
[2025-04-08T21:15:35.476+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'insert_wind_data', 'scheduled__2025-04-08T21:14:00+00:00', '--job-id', '898', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmp85bptvvh']
[2025-04-08T21:15:35.478+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20613) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:15:35.480+0000] {standard_task_runner.py:72} INFO - Started process 20617 to run task
[2025-04-08T21:15:35.479+0000] {standard_task_runner.py:105} INFO - Job 898: Subtask insert_wind_data
[2025-04-08T21:15:35.550+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.insert_wind_data scheduled__2025-04-08T21:14:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:15:35.640+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_wind_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:14:00+00:00'
[2025-04-08T21:15:35.641+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:15:35.655+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:15:35.972+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:15:35.976+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:15:35.977+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=insert_wind_data, run_id=scheduled__2025-04-08T21:14:00+00:00, execution_date=20250408T211400, start_date=20250408T211535, end_date=20250408T211535
[2025-04-08T21:15:35.999+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:15:36.008+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T21:15:36.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
