[2025-04-08T21:21:00.574+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:21:00.602+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:19:00+00:00 [queued]>
[2025-04-08T21:21:00.617+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:19:00+00:00 [queued]>
[2025-04-08T21:21:00.618+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:21:00.668+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_weather_table> on 2025-04-08 21:19:00+00:00
[2025-04-08T21:21:00.689+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21106) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:21:00.694+0000] {standard_task_runner.py:72} INFO - Started process 21126 to run task
[2025-04-08T21:21:00.701+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_dim_weather_table', 'scheduled__2025-04-08T21:19:00+00:00', '--job-id', '909', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmphvkpf3iu']
[2025-04-08T21:21:00.710+0000] {standard_task_runner.py:105} INFO - Job 909: Subtask create_dim_weather_table
[2025-04-08T21:21:00.792+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_dim_weather_table scheduled__2025-04-08T21:19:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:21:00.911+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_dim_weather_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:19:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:19:00+00:00'
[2025-04-08T21:21:00.915+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:21:00.938+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:21:00.995+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:21:01.017+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:21:01.019+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_dim_weather_table, run_id=scheduled__2025-04-08T21:19:00+00:00, execution_date=20250408T211900, start_date=20250408T212100, end_date=20250408T212101
[2025-04-08T21:21:01.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:21:01.108+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
